document.addEventListener("DOMContentLoaded", () => {
    let globalData = null;

    // Tab Navigation Switcher (Centered Top Header / Mobile Bottom Bar)
    const navTabs = document.querySelectorAll(".nav-tab");
    const tabPages = document.querySelectorAll(".tab-page");
    const pageTitle = document.getElementById("page-title");

    const tabTitles = {
        "tab-overview": "Tổng Quan Phân Tích Định Lượng XSMB",
        "tab-top20": "Bảng Xếp Hạng Top 20 Đồng Thuận Super-Score",
        "tab-matrix3d": "Dự Đoán Ba Càng (3D) & Cầu Ghép Động",
        "tab-backtest": "Kiểm Chứng Backtest & Quản Lý Vốn Kelly",
        "tab-elimination": "Bộ Lọc Loại Trừ Số Rác & Cảnh Báo Risk"
    };

    navTabs.forEach(item => {
        item.addEventListener("click", () => {
            const targetTab = item.getAttribute("data-tab");

            navTabs.forEach(i => i.classList.remove("active"));
            tabPages.forEach(p => p.classList.remove("active"));

            item.classList.add("active");
            const activePage = document.getElementById(targetTab);
            if (activePage) {
                activePage.classList.add("active");
            }

            if (tabTitles[targetTab]) {
                pageTitle.textContent = tabTitles[targetTab];
            }

            window.scrollTo({ top: 0, behavior: 'smooth' });
        });
    });

    // Toast Notification Handler
    function showToast(message) {
        const toast = document.getElementById("toast-notification");
        if (!toast) return;
        toast.textContent = message;
        toast.classList.add("show");
        setTimeout(() => {
            toast.classList.remove("show");
        }, 2500);
    }

    // Helper: Copy text to clipboard
    function copyToClipboard(text, countInfo) {
        if (!text) {
            showToast("❌ Không có dàn số để copy");
            return;
        }

        if (navigator.clipboard && window.isSecureContext) {
            navigator.clipboard.writeText(text).then(() => {
                showToast(`✅ Đã copy dàn ${countInfo} vào bộ nhớ tạm!`);
            }).catch(err => {
                fallbackCopyTextToClipboard(text, countInfo);
            });
        } else {
            fallbackCopyTextToClipboard(text, countInfo);
        }
    }

    function fallbackCopyTextToClipboard(text, countInfo) {
        const textArea = document.createElement("textarea");
        textArea.value = text;
        textArea.style.top = "0";
        textArea.style.left = "0";
        textArea.style.position = "fixed";
        document.body.appendChild(textArea);
        textArea.focus();
        textArea.select();
        try {
            document.execCommand('copy');
            showToast(`✅ Đã copy dàn ${countInfo} vào bộ nhớ tạm!`);
        } catch (err) {
            showToast("❌ Không thể copy dàn số");
        }
        document.body.removeChild(textArea);
    }

    // Load JSON dataset generated by daily_runner.py
    fetch("dashboard_data.json")
        .then(res => res.json())
        .then(data => {
            globalData = data;
            renderDashboard(data);
        })
        .catch(err => {
            console.error("Could not load dashboard_data.json:", err);
            document.getElementById("latest-draw-info").textContent = "Lỗi tải dữ liệu. Hãy chạy python daily_runner.py";
        });

    function renderDashboard(data) {
        const meta = data.metadata || {};
        const analytics = data.analytics || {};
        const risk = data.risk_and_finance || {};
        const frame3d = analytics.frame_3days || {};

        // Render Metadata
        if (meta.latest_draw) {
            document.getElementById("latest-draw-info").textContent = 
                `Kỳ quay: ${meta.latest_draw.date} | GĐB: ${meta.latest_draw.gdb} (Đề ${meta.latest_draw.de_2d})`;
        }

        // Render Reset Summary String
        if (frame3d.last_draw_summary) {
            const resetSummaryEl = document.getElementById("reset-summary-str");
            if (resetSummaryEl) resetSummaryEl.textContent = frame3d.last_draw_summary;
        }

        // Render Header Badges
        const bt = risk.backtest_metrics || {};
        document.getElementById("k3n-rate").textContent = `${bt.n3_win_rate_estimate || 87.5}%`;
        document.getElementById("mdd-val").textContent = `${bt.max_drawdown_percent || 0}%`;
        document.getElementById("vol-status").textContent = risk.volatility_info?.status || "STABLE";

        // Render Overview Metrics
        const markov = analytics.markov_predictions || {};
        const heads = markov.top_heads ? markov.top_heads.map(h => `Đầu ${h[0]}`).join(", ") : "--";
        const tails = markov.top_tails ? markov.top_tails.map(t => `Đuôi ${t[0]}`).join(", ") : "--";
        
        document.getElementById("markov-heads").textContent = heads;
        document.getElementById("markov-tails").textContent = tails;

        const kelly = risk.staking_recommendation || {};
        document.getElementById("kelly-stake").textContent = `${(kelly.recommended_stake_vnd || 0).toLocaleString()} VNĐ`;
        document.getElementById("kelly-percent").textContent = `Tỷ lệ: ${kelly.recommended_percent || 0}% ngân sách`;

        const elim = analytics.elimination_summary || {};
        document.getElementById("elim-count").textContent = `${elim.eliminated_count || 0} số`;

        // RENDER EXPLICIT DATES AND NUMBERS FOR N1, N2, N3
        if (frame3d.n1) {
            document.getElementById("n1-date-str").textContent = `📅 ${frame3d.n1.date}`;
            document.getElementById("n1-count").textContent = `${frame3d.n1.count} số`;
            if (frame3d.n1.description) document.getElementById("n1-desc-str").textContent = frame3d.n1.description;
            renderFrameNumbers("n1-numbers-container", frame3d.n1.numbers || []);
        }

        if (frame3d.n2) {
            document.getElementById("n2-date-str").textContent = `📅 ${frame3d.n2.date}`;
            document.getElementById("n2-count").textContent = `${frame3d.n2.count} số`;
            if (frame3d.n2.description) document.getElementById("n2-desc-str").textContent = frame3d.n2.description;
            renderFrameNumbers("n2-numbers-container", frame3d.n2.numbers || []);
        }

        if (frame3d.n3) {
            document.getElementById("n3-date-str").textContent = `📅 ${frame3d.n3.date}`;
            document.getElementById("n3-count").textContent = `${frame3d.n3.count} số`;
            if (frame3d.n3.description) document.getElementById("n3-desc-str").textContent = frame3d.n3.description;
            renderFrameNumbers("n3-numbers-container", frame3d.n3.numbers || []);
        }

        // RENDER DUAL-FRAME OVERLAP NUMBERS (OPTION C)
        const combinedNums = frame3d.dual_frame_options?.option_combined?.numbers || [];
        renderFrameNumbers("combined-numbers-container", combinedNums);

        // SETUP COPY BUTTON EVENT LISTENERS
        setupCopyButtons(frame3d, analytics);

        // Render Top 20 Table
        const top20Body = document.getElementById("top20-table-body");
        if (top20Body) {
            top20Body.innerHTML = "";
            (analytics.top20_consensus || []).forEach((item, index) => {
                const tr = document.createElement("tr");
                tr.innerHTML = `
                    <td>Top ${String(index + 1).padStart(2, '0')}</td>
                    <td><strong class="text-accent">${item.number}</strong></td>
                    <td>Tổng ${item.sum}</td>
                    <td>${item.gan_days}N</td>
                    <td>${item.f30}L</td>
                    <td>${item.f60}L</td>
                    <td><strong>${item.super_score}</strong></td>
                    <td>${item.g7_valid ? '<span class="text-success">CÓ</span>' : '<span class="text-danger">KHÔNG</span>'}</td>
                `;
                top20Body.appendChild(tr);
            });
        }

        // Render 3D Matrix Table
        const matrixBody = document.getElementById("matrix3d-table-body");
        if (matrixBody) {
            matrixBody.innerHTML = "";
            (analytics.top_3d || []).forEach((item, index) => {
                const tr = document.createElement("tr");
                tr.innerHTML = `
                    <td>Top ${String(index + 1).padStart(2, '0')}</td>
                    <td>${item.cang}</td>
                    <td><strong class="text-accent">${item.number_3d}</strong></td>
                    <td>${item.base_2d}</td>
                    <td>${item.consensus_score}</td>
                    <td><span class="text-success">${item.classification}</span></td>
                `;
                matrixBody.appendChild(tr);
            });
        }

        // Render Backtest & Kelly Lists
        const backtestList = document.getElementById("backtest-info-list");
        if (backtestList) {
            backtestList.innerHTML = `
                <li><span>Tổng số ngày thử nghiệm:</span> <strong>${bt.total_days_tested || 0} ngày</strong></li>
                <li><span>Tỷ lệ trúng Khung 1 Ngày (N1):</span> <strong class="text-accent">${bt.n1_win_rate || 0}%</strong></li>
                <li><span>Tỷ lệ trúng Khung 2 Ngày (N2):</span> <strong class="text-success">${bt.n2_win_rate_estimate || 0}%</strong></li>
                <li><span>Tỷ lệ trúng Khung 3 Ngày (N3 Max):</span> <strong class="text-success">${bt.n3_win_rate_estimate || 0}%</strong></li>
                <li><span>Max Drawdown (Sụt giảm vốn tối đa):</span> <strong class="text-warning">${bt.max_drawdown_percent || 0}%</strong></li>
                <li><span>Chỉ số Sharpe (Sharpe Ratio):</span> <strong>${bt.sharpe_ratio || 0}</strong></li>
                <li><span>Vốn ban đầu / Vốn hiện tại:</span> <strong>10,000,000 / ${(bt.final_bankroll || 10000000).toLocaleString()} VNĐ</strong></li>
            `;
        }

        const kellyList = document.getElementById("kelly-info-list");
        if (kellyList) {
            kellyList.innerHTML = `
                <li><span>Tổng ngân sách khả dụng:</span> <strong>${(kelly.bankroll || 10000000).toLocaleString()} VNĐ</strong></li>
                <li><span>Giai đoạn khung nuôi:</span> <strong class="text-accent">${kelly.frame_stage || 'N1'}</strong></li>
                <li><span>Tỷ lệ phân bổ ngân sách:</span> <strong class="text-success">${kelly.recommended_percent || 0}%</strong></li>
                <li><span>Số tiền đặt cược khuyến nghị:</span> <strong class="text-accent">${(kelly.recommended_stake_vnd || 0).toLocaleString()} VNĐ</strong></li>
                <li><span>Đánh giá độ rủi ro:</span> <strong class="${kelly.risk_level === 'LOW' ? 'text-success' : 'text-warning'}">${kelly.risk_level || 'LOW'}</strong></li>
            `;
        }

        // Render Elimination Table
        const elimBody = document.getElementById("elim-table-body");
        if (elimBody) {
            elimBody.innerHTML = "";
            (elim.eliminated_sample || []).forEach(item => {
                const tr = document.createElement("tr");
                tr.innerHTML = `
                    <td><strong class="text-danger">${item[0]}</strong></td>
                    <td>${item[1]}</td>
                `;
                elimBody.appendChild(tr);
            });
        }

        // Initialize Live Filter Controls
        setupFilters(analytics.top40_consensus || []);
    }

    function renderFrameNumbers(containerId, numbers) {
        const container = document.getElementById(containerId);
        if (!container) return;
        container.innerHTML = "";
        numbers.forEach(num => {
            const span = document.createElement("span");
            span.className = "pill-sm";
            span.textContent = num;
            container.appendChild(span);
        });
    }

    function setupCopyButtons(frame3d, analytics) {
        // Copy N1
        const btnN1 = document.getElementById("btn-copy-n1");
        if (btnN1) {
            btnN1.onclick = () => {
                const nums = frame3d.n1?.numbers || [];
                copyToClipboard(nums.join(", "), `${nums.length} số Dàn N1`);
            };
        }

        // Copy N2
        const btnN2 = document.getElementById("btn-copy-n2");
        if (btnN2) {
            btnN2.onclick = () => {
                const nums = frame3d.n2?.numbers || [];
                copyToClipboard(nums.join(", "), `${nums.length} số Dàn N2`);
            };
        }

        // Copy N3
        const btnN3 = document.getElementById("btn-copy-n3");
        if (btnN3) {
            btnN3.onclick = () => {
                const nums = frame3d.n3?.numbers || [];
                copyToClipboard(nums.join(", "), `${nums.length} số Dàn N3`);
            };
        }

        // Copy Combined Overlap
        const btnCombined = document.getElementById("btn-copy-combined");
        if (btnCombined) {
            btnCombined.onclick = () => {
                const nums = frame3d.dual_frame_options?.option_combined?.numbers || [];
                copyToClipboard(nums.join(", "), `${nums.length} số Giao Thoa`);
            };
        }

        // Copy Top 20
        const btnTop20 = document.getElementById("btn-copy-top20");
        if (btnTop20) {
            btnTop20.onclick = () => {
                const nums = (analytics.top20_consensus || []).map(t => t.number);
                copyToClipboard(nums.join(", "), `${nums.length} số Top 20`);
            };
        }

        // Copy Top 3D
        const btn3d = document.getElementById("btn-copy-3d");
        if (btn3d) {
            btn3d.onclick = () => {
                const nums = (analytics.top_3d || []).map(t => t.number_3d);
                copyToClipboard(nums.join(", "), `${nums.length} số Ba Càng 3D`);
            };
        }
    }

    function setupFilters(top40) {
        const sumSelect = document.getElementById("filter-sum");
        const touchSelect = document.getElementById("filter-touch");
        const container = document.getElementById("filtered-numbers-container");
        const btnCopyFiltered = document.getElementById("btn-copy-filtered");

        if (!sumSelect || !touchSelect || !container) return;

        let currentFilteredList = [];

        function applyFilter() {
            const selSum = sumSelect.value;
            const selTouch = touchSelect.value;

            currentFilteredList = top40.filter(item => {
                const matchSum = (selSum === "ALL") || (String(item.sum) === selSum);
                const matchTouch = (selTouch === "ALL") || (item.number.includes(selTouch));
                return matchSum && matchTouch;
            });

            container.innerHTML = "";
            if (currentFilteredList.length === 0) {
                container.innerHTML = "<p class='text-muted'>Không tìm thấy con số thỏa mãn bộ lọc hiện tại.</p>";
                return;
            }

            currentFilteredList.forEach(item => {
                const pill = document.createElement("div");
                pill.className = "pill";
                pill.innerHTML = `${item.number} <span class="score">(${item.super_score} đ)</span>`;
                container.appendChild(pill);
            });
        }

        if (btnCopyFiltered) {
            btnCopyFiltered.onclick = () => {
                const nums = currentFilteredList.map(t => t.number);
                copyToClipboard(nums.join(", "), `${nums.length} số Đã Lọc`);
            };
        }

        sumSelect.addEventListener("change", applyFilter);
        touchSelect.addEventListener("change", applyFilter);
        applyFilter();
    }
});
